sudo: true
language: generic

git:
  depth: 5

cache:
  directories:
  - "$HOME/.cabal"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:
  - ghc: 8.2.2
    env: GHCVER='8.2.2' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.2.2
        - cabal-install-head

  - ghc: 8.4.4
    env: GHCVER='8.4.4' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.4.4
        - cabal-install-head

  - ghc: 8.6.2
    env: GHCVER='8.6.2' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.6.2
        - cabal-install-head

  - ghc: 8.2.2
    env: GHCVER='8.2.2' STACK_YAML="$TRAVIS_BUILD_DIR/stack-$GHCVER.yaml"
    os: linux
    addons:
      apt:
        packages:
        - libgmp-dev

  - ghc: 8.4.4
    env: GHCVER='8.4.4' STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml" DEPLOY=yes
    os: linux
    addons:
      apt:
        packages:
        - libgmp-dev

  - ghc: 8.6.2
    env: GHCVER='8.6.2' STACK_YAML="$TRAVIS_BUILD_DIR/stack-$GHCVER.yaml"
    os: linux
    addons:
      apt:
        packages:
        - libgmp-dev

  # macOS build
  - ghc: 8.4.4
    env: GHCVER='8.4.4' STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml" DEPLOY=yes
    os: osx
    addons:
      apt:
        packages:
        - libgmp-dev

install:
  - |
    if [ -z "$STACK_YAML" ]; then
      export PATH="/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH"
      echo $PATH
      cabal new-update
      cabal new-build all --enable-tests --enable-benchmarks
    else
      mkdir -p ~/.local/bin
      export PATH="$HOME/.local/bin:$PATH"

      # install stack
      export STACK_URL="https://www.stackage.org/stack/${TRAVIS_OS_NAME}-x86_64"
      echo "Download stack from: $STACK_URL"
      cd /tmp
      curl --location "$STACK_URL" > stack.tar.gz
      tar xz --strip-components=1 --file=stack.tar.gz -C ~/.local/bin/
      cd -

      # build project with stack
      stack --version
      stack setup --no-terminal --install-cabal 2.2.0.1
      stack ghc -- --version
      stack build --only-dependencies --no-terminal
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal new-test all
    else
      stack build --test --no-terminal
    fi
  - curl https://raw.githubusercontent.com/kowainik/relude/988bbdd3a09df1159917012933780523644880e5/.hlint.yaml -o .hlint-relude.yaml
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint -h .hlint-relude.yaml summoner-cli/src/ summoner-cli/test/ summoner-tui/src/

after_success:
  - echo "Trying to deploy..."
  - |
    if [ "$DEPLOY" = "yes" ]; then
      echo "Deploy triggered!"
      mv "$(stack path --local-install-root)/bin/summon"     "summon-cli-${TRAVIS_OS_NAME}"
      mv "$(stack path --local-install-root)/bin/summon-tui" "summon-tui-${TRAVIS_OS_NAME}"
      chmod +x "summon-cli-${TRAVIS_OS_NAME}"
      chmod +x "summon-tui-${TRAVIS_OS_NAME}"
      git tag "$(date +'%Y%m%d%H%M%S')"
    fi

deploy:
  - skip_cleanup: true
    provider: releases
    api_key:
      secure: XhNZ1oniO2dABEFsTuWr0NxzcIGHDwF/MgamGpqkk64TslJngRgsKsiaHQQSOYKtMpF6bwoJ31mLA6EfIu7e7DFSvFCYmwEci/rPXLZVyrmNGWyby2K0MGuLQNdacEJATrwmuxnPTdc1zqm9AK/iGu9hcHBgsGpWpQur3E2g9A+IokTZ7gGqz2I/INk/YCS6YvjYulrSqFxhBTOdFKY4UlUM4KzVANZVCOrSx7kveH01vX7mYMIPxKR+pdD+7jya/jLZHnzXahMWlktiUG5pqebkNfgnJo6x/x/jTQwg3W80XKAm1RdRXsSTVCFGsuYpo/Jkd81Q5/mYYWhZYyX90dPInlYW0PtEuPkVIpG60waFAz58SHpWdMH6hVRxAnwvOOeT5pgEmMDXovy7Dl5YF37JqxqJ+LDFr97H/Zp16h9njKcU1GEWEkMTKxsyCgOu1gpHT1oby7UU4bMkDGQ9HjUhaE+n5kGUZ9brNDYI7223C+cyEW3pQgDIhXTh2kuRyM+RbJOcgxbHtO5uMqP12P0dLXlPfbohUMsSfwWbIQGGIY4EKY2wc1DYILQ6moj5FYlBb381mb/J7pIhuerRNgtocQhaHe47KjP+diWmVe1BuypOTUuS2Hrf5TGqurRiJeH4+bHjxhHbDFH7RbsaNbeupp2J4mHsGIKeHeQHZJY=
    file:
      - "summon-cli-${TRAVIS_OS_NAME}"
      - "summon-tui-${TRAVIS_OS_NAME}"
    on:
      repo: kowainik/summoner
      tags: true
      condition: $DEPLOY = yes

notifications:
  email: false
  slack:
    rooms:
      - kowainik:n60CMbB0kfJHRmYKIPmjf7Tp
    on_success: change
    on_failure: always
