sudo: true
language: generic

git:
  depth: 5

cache:
  directories:
  - "$HOME/.cabal"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:
  - ghc: 8.2.2
    env: GHCVER='8.2.2' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.2.2
        - cabal-install-head

  - ghc: 8.4.4
    env: GHCVER='8.4.4' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.4.4
        - cabal-install-head

  - ghc: 8.6.2
    env: GHCVER='8.6.2' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.6.2
        - cabal-install-head

  - ghc: 8.2.2
    env: GHCVER='8.2.2' STACK_YAML="$TRAVIS_BUILD_DIR/stack-$GHCVER.yaml"
    os: linux
    addons:
      apt:
        packages:
        - libgmp-dev

  - ghc: 8.4.4
    env: GHCVER='8.4.4' STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"
    os: linux
    addons:
      apt:
        packages:
        - libgmp-dev

  - ghc: 8.6.2
    env: GHCVER='8.6.2' STACK_YAML="$TRAVIS_BUILD_DIR/stack-$GHCVER.yaml"
    os: linux
    addons:
      apt:
        packages:
        - libgmp-dev

install:
  - |
    if [ -z "$STACK_YAML" ]; then
      export PATH="/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH"
      echo $PATH
      cabal new-update
      cabal new-build all --enable-tests --enable-benchmarks
    else
      mkdir -p ~/.local/bin
      export PATH="$HOME/.local/bin:$PATH"
      travis_retry curl -L 'https://www.stackage.org/stack/linux-x86_64' | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      stack --version
      stack setup --no-terminal --install-cabal 2.2.0.1
      stack ghc -- --version
      stack build --only-dependencies --no-terminal
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal new-test all
    else
      stack build --test --no-terminal
    fi
  - curl https://raw.githubusercontent.com/kowainik/relude/988bbdd3a09df1159917012933780523644880e5/.hlint.yaml -o .hlint-relude.yaml
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint -h .hlint-relude.yaml summoner-cli/src/ summoner-cli/test/ summoner-tui/src/

notifications:
  email: false
  slack:
    rooms:
      - kowainik:n60CMbB0kfJHRmYKIPmjf7Tp
    on_success: change
    on_failure: always
