clone_folder: "c:\\WORK"
clone_depth: 5

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# build only main branch
branches:
  only:
    - main

platform:
  - x86_64

cache:
  - "C:\\SR"
  - dist-newstyle

environment:
  global:
    CABOPTS: --store-dir=C:\\SR

  matrix:
    - GHCVER: 9.12.3

install:
  - choco source add -n mistuke -s https://www.myget.org/F/mistuke/api/v2
  - choco install -y cabal --version 3.6.2.0
  - choco install -y ghc   --version 9.12.3
  - refreshenv

before_build:
  - cabal --version
  - ghc   --version
  - cabal %CABOPTS% update

build_script:
  - cabal %CABOPTS% configure --enable-tests --enable-benchmarks --enable-documentation --test-show-details=direct --write-ghc-environment-files=always
  - cabal %CABOPTS% build all
  - cabal %CABOPTS% test  all
